root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -ldflags=\"-s -w -extldflags \"-static\"\" -o ./.tmp/twitter-clone/rest cmd/rest/main.go"
bin = ".tmp/twitter-clone"
full_bin = "./.tmp/twitter-clone/rest --prefork"
delay = 1000

log = "air_errors.log"

include_ext = ["go", "mod", "yaml", "env"]
exclude_dir = [".tmp", "node_modules", "web"]

[log]
time = true

[misc]
clean_on_exit = true
